_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
DATASETS:
  TRAIN: "COCO_train_vertebre"
  TEST:"COCO_test_vertebre"
SOLVER:
  STEPS: (20000, 300000)
  MAX_ITER: 34000
  IMS_PER_BATCH : 2 
  BASE_LR : 0.0025
